/** Nội dung UI mẫu của màn 37; không phải DTO hoặc kết quả xác minh thực. */
export const CAMERA_CHECK_CONTENT = {
  brand: "LegacyVault",
  documents: {
    title: "Đọc thông tin căn cước",
    description: "Thêm mặt trước để bắt đầu. Với thẻ mới, thêm mặt sau để lấy nơi cư trú.",
    preview: "Bản xem trước UI · Ảnh không được tải lên hoặc xử lý OCR.",
    papers: "Giấy tờ của bạn",
    sides: ["Mặt trước", "Mặt sau"] as const,
    choose: "Chọn ảnh căn cước",
    drop: "Kéo ảnh vào khung hoặc bấm để chọn",
    hint: "Chọn ảnh rõ nét, đủ bốn góc, không bị lóa hoặc che khuất.",
    formats: "JPG, PNG, WebP · Tối đa 8 MB",
    accept: "image/jpeg,image/png,image/webp",
    maxBytes: 8 * 1024 * 1024,
    invalid: "Vui lòng chọn ảnh JPG, PNG hoặc WebP không quá 8 MB.",
    empty: "Chưa chọn ảnh",
    selected: "Đã chọn ảnh trên thiết bị",
    read: "Đọc thông tin",
    notice: "OCR chưa được kết nối. Chưa đọc hoặc xác minh thông tin căn cước.",
    identity: "Thông tin nhận diện",
    identityHint: "Thông tin sẽ xuất hiện tại đây sau khi đọc giấy tờ. Hiện chưa có dữ liệu xác minh.",
    fields: ["Số căn cước", "Họ và tên", "Nơi cư trú / địa chỉ thường trú"],
    waiting: "Chờ đọc giấy tờ",
    continue: "Tiếp tục so khớp mặt",
    cameraPreview: "Xem trước màn so khớp khuôn mặt",
    back: "Quay lại giấy tờ",
  },
  title: "Bạn đang ở trước camera.",
  description:
    "Giữ khuôn mặt trong khung và làm theo hướng dẫn. Chỉ lấy selfie khi phiên đạt thử thách.",
  preview: "Bản xem trước UI · Chưa kết nối camera hoặc dịch vụ xác minh.",
  menuLabel: "Menu Người nhận",
  navigation: ["Tổng quan", "Xác minh", "Nội dung nhận", "Lời nhắn"],
  unavailable: "Màn hình này chưa được dựng trong bản xem trước.",
  user: "Con trưởng",
  avatar: "C",
  role: "Người nhận",
  logout: "Đăng xuất",
  progressLabel: "Tiến trình xác minh mẫu",
  steps: [
    { title: "Đọc căn cước", detail: "Thông tin và nơi cư trú", complete: true },
    { title: "So khớp khuôn mặt", detail: "Căn cước và ảnh chân dung", complete: true },
    { title: "Kiểm tra camera", detail: "Thử thách trực tiếp", complete: false },
  ],
  camera: "Camera trực tiếp",
  off: "Đang tắt",
  cameraOff: "Camera đang tắt",
  startHint: "Mở camera để bắt đầu",
  guide: "Giữ đủ sáng, bỏ khẩu trang và đặt mặt trong khung hướng dẫn.",
  open: "Mở camera",
  close: "Tắt camera",
  begin: "Bắt đầu thử thách",
  scaffoldNotice:
    "Camera chưa được kết nối trong bản UI này. Chưa chụp ảnh hoặc gửi dữ liệu xác minh.",
  advanced: "Thử riêng ảnh chống giả mạo",
  advancedTag: "Nâng cao",
  upload: "Chọn ảnh để kiểm tra",
  advancedNote: "Kiểm tra một ảnh không thay thế thử thách trực tiếp.",
  challengesTitle: "Tiến trình thử thách",
  notStarted: "Chưa chạy",
  instructions: "Làm theo thứ tự hệ thống đưa ra. Các động tác sẽ sáng lên khi bắt đầu.",
  challenges: ["Nhìn thẳng vào camera", "Quay đầu sang trái", "Chớp mắt hai lần"],
  metrics: [
    { label: "Động tác", value: "Chưa kiểm tra" },
    { label: "Chống giả mạo", value: "—" },
    { label: "Khung hình đã đánh giá", value: "0" },
    { label: "Thời gian còn lại", value: "—" },
  ],
  finishHint: "Hoàn thành động tác và đạt chống giả mạo để chuyển selfie sang màn so khớp.",
  useSelfie: "Dùng selfie để so khớp",
  disclaimer:
    "Xác minh cơ bản, không có giá trị pháp lý. LegacyVault không thay thế di chúc. Chưa xác thực giấy tờ thật/giả hoặc bảo đảm chống deepfake.",
} as const;
