/** Nội dung cài đặt UI, dữ liệu mẫu không gắn với tài khoản thật. */
export const SETTINGS_UI_CONTENT = {
  title: "Cài đặt",
  description: "Thông tin cá nhân, điểm danh và bảo mật tài khoản.",
  profile: "Hồ sơ",
  save: "Lưu thay đổi",
  heartbeat: "Điểm danh định kỳ",
  reminders: [
    {
      title: "Chu kỳ điểm danh",
      detail: "Chu kỳ minh họa; cấu hình thực do backend xác nhận",
      value: "30 ngày · mẫu",
      enabled: false,
    },
    {
      title: "Nhắc trước khi đến hạn",
      detail: "Gửi email trước 7 ngày và 1 ngày",
      value: "",
      enabled: true,
    },
    {
      title: "Nhắc qua tin nhắn",
      detail: "Dùng số điện thoại đã đăng ký",
      value: "",
      enabled: false,
    },
  ],
  securityTitle: "Bảo mật",
  account: "Tài khoản",
  accountHint: "Tải dữ liệu hoặc yêu cầu xóa tài khoản. Xóa tài khoản không thể hoàn tác.",
  export: "Tải dữ liệu",
  delete: "Xóa tài khoản",
  viewDevices: "Xem thiết bị đang đăng nhập",
  back: "Quay lại cài đặt",
  nav: "Nhóm cài đặt",
  tabs: [
    { id: "profile", label: "Thông tin cá nhân" },
    { id: "security", label: "Bảo mật" },
    { id: "sessions", label: "Thiết bị & phiên" },
  ],
  waiting: "Chưa có dữ liệu từ dịch vụ tài khoản",
  sample: "Tài khoản minh họa",
  fields: [
    { label: "Họ và tên", value: "Người dùng mẫu", type: "text" },
    { label: "Email", value: "demo@example.invalid", type: "email" },
    { label: "Số điện thoại", value: "", type: "tel" },
    { label: "Ngày sinh", value: "", type: "date" },
  ],
  edit: "Chỉnh sửa thông tin",
  disabled: "Chưa kết nối dịch vụ tài khoản",
  security: [
    {
      title: "Mật khẩu đăng nhập",
      detail: "Đổi mật khẩu cần xác nhận bằng phiên hợp lệ và phản hồi từ backend.",
      action: "Đổi mật khẩu",
    },
    {
      title: "Passkey",
      detail: "Đăng ký khóa truy cập trên thiết bị hỗ trợ WebAuthn.",
      action: "Thêm Passkey",
    },
    {
      title: "Xác thực hai bước",
      detail: "Theo chính sách vai trò và trạng thái tài khoản từ backend.",
      action: "Thiết lập xác thực",
    },
  ],
  devices: "Các phiên đăng nhập",
  device: "Trình duyệt mẫu trên máy tính",
  deviceHint: "Phiên minh họa · Không phải thông tin thiết bị thực",
  revoke: "Đăng xuất phiên",
  revokeAll: "Đăng xuất các phiên khác",
  emptySessions: "Chưa có danh sách phiên thực",
  noSession: "Backend phải xác nhận phiên hiện tại và quyền thu hồi trước khi cho thao tác.",
} as const;
